import re

file_path = r'c:\Users\rizky_11yf1be\Desktop\Tugas_Akhir\backend\package\yunesa\knowledge\base.py'
with open(file_path, 'r', encoding='utf-8') as f:
    text = f.read()

translations = [
    (r'\"\"\"知识库统一异常基类\"\"\"', r'\"\"\"Base class for knowledge base exceptions\"\"\"'),
    (r'\"\"\"知识库不存在错误\"\"\"', r'\"\"\"Knowledge base not found error\"\"\"'),
    (r'\"\"\"知识库操作错误\"\"\"', r'\"\"\"Knowledge base operation error\"\"\"'),
    (r'\"\"\"知识库抽象基类，定义统一接口\"\"\"', r'\"\"\"Abstract base class for knowledge base, defining a unified interface\"\"\"'),
    (r'# 类级别的处理队列，跟踪所有正在处理的文件', r'# Class-level processing queue to track all files being processed'),
    (r'初始化知识库', r'Initialize knowledge base'),
    (r'work_dir: 工作目录', r'work_dir: Working directory'),
    (r'# 标记元数据是否已加载', r'# Flag to track if metadata is loaded'),
    (r'# 初始化类级别的锁', r'# Initialize class-level lock'),
    (r'# 注意：不在 __init__ 中加载元数据，由 KnowledgeBaseManager 统一管理加载', r'# Note: Metadata is not loaded in __init__, managed by KnowledgeBaseManager'),
    (r'\"\"\"由 KnowledgeBaseManager 调用，同步加载元数据\"\"\"', r'\"\"\"Called by KnowledgeBaseManager to synchronously load metadata\"\"\"'),
    (r'# 过滤出当前 kb_type 的知识库', r'# Filter knowledge bases of current kb_type'),
    (r'# 过滤文件', r'# Filter files'),
    (r'# 过滤评估基准', r'# Filter evaluation benchmarks'),
    (r'加载了 \{\} 个数据库的元数据', r'Loaded metadata for {} databases'),
    (r'\"\"\"确保元数据已加载（延迟加载）\"\"\"', r'\"\"\"Ensure metadata is loaded (lazy loading)\"\"\"'),
    (r'元数据尚未加载，请确保 KnowledgeBaseManager 已调用 load_metadata\(\)', r'Metadata not loaded yet, ensure KnowledgeBaseManager has called load_metadata()'),
    (r'\"\"\"知识库类型标识\"\"\"', r'\"\"\"Knowledge base type identifier\"\"\"'),
    (r'创建底层知识库实例', r'Create underlying knowledge base instance'),
    (r'db_id: 数据库ID', r'db_id: Database ID'),
    (r'config: 配置信息', r'config: Configuration information'),
    (r'底层知识库实例', r'Underlying knowledge base instance'),
    (r'初始化底层知识库实例', r'Initialize underlying knowledge base instance'),
    (r'instance: 底层知识库实例', r'instance: Underlying knowledge base instance'),
    (r'创建数据库记录', r'Create database record'),
    (r'创建数据库', r'Create database'),
    (r'database_name: 数据库名称', r'database_name: Database name'),
    (r'description: 数据库描述', r'description: Database description'),
    (r'embed_info: 嵌入模型信息', r'embed_info: Embed model information'),
    (r'llm_info: LLM配置信息', r'llm_info: LLM configuration information'),
    (r'\*\*kwargs: 其他配置参数', r'**kwargs: Other configuration parameters'),
    (r'数据库信息字典', r'Database information dictionary'),
    (r'# 从 kwargs 中获取 is_private 配置', r'# Get is_private config from kwargs'),
    (r'# 确保 Pydantic 模型被转换为字典，以便 JSON 序列化', r'# Ensure Pydantic models are converted to dicts for JSON serialization'),
    (r'# 创建工作目录', r'# Create working directory'),
    (r'# 返回数据库信息', r'# Return database info'),
    (r'删除数据库', r'Delete database'),
    (r'操作结果', r'Operation result'),
    (r'# 1. 删除文件元数据中记录的 MinIO 文件', r'# 1. Delete MinIO files recorded in file metadata'),
    (r'# 删除解析后的 markdown 文件', r'# Delete parsed markdown file'),
    (r'# 2. 并行删除所有知识库 bucket 中该 db_id 下的文件', r'# 2. Parallel deletion of all files under this db_id in knowledge base buckets'),
    (r'# 3. 删除数据库记录', r'# 3. Delete database record'),
    (r'# 删除工作目录', r'# Delete working directory'),
    (r'删除成功', r'Deleted successfully'),
    (r'更新内容 - 根据file_ids重新解析文件并更新向量库', r'Update content - re-parse files and update vector store based on file_ids'),
    (r'file_ids: 文件ID列表', r'file_ids: List of file IDs'),
    (r'params: 处理参数', r'params: Processing parameters'),
    (r'更新结果列表', r'List of update results'),
    (r'异步查询知识库', r'Asynchronous query knowledge base'),
    (r'query_text: 查询文本', r'query_text: Query text'),
    (r'\*\*kwargs: 查询参数', r'\*\*kwargs: Query parameters'),
    (r'一个包含字典的列表，每个字典代表一个检索到的文档块。', r'A list containing dictionaries, each representing a retrieved document chunk.'),
    (r'获取知识库类型的查询参数配置', r'Get query parameter configurations of the knowledge base type'),
    (r'\*\*kwargs: 额外参数\(如 reranker_names 等\)', r'**kwargs: Extra parameters (like reranker_names, etc.)'),
    (r'同步查询知识库（兼容性方法）', r'Synchronous query knowledge base (compatibility method)'),
    (r'\"\"\"从实例元数据中加载查询参数\"\"\"', r'\"\"\"Load query parameters from instance metadata\"\"\"'),
    (r'获取数据库详细信息', r'Get detailed database information'),
    (r'include_files: 是否包含文件信息，默认为True（保持向后兼容）', r'include_files: Whether to include file info, default is True (backward compatibility)'),
    (r'数据库信息或None', r'Database info or None'),
    (r'# 检查并修复异常的processing状态', r'# Check and fix anomalous processing status'),
    (r'# 统计文件数量（始终计算，即使不加载文件详情）', r'# Count number of files (always calculate even if not loading file details)'),
    (r'# 仅在需要时加载文件详情', r'# Only load file details when needed'),
    (r'# 按创建时间倒序排序文件列表', r'# Sort file list by creation time in descending order'),
    (r'已连接', r'Connected'),
    (r'获取所有数据库信息', r'Get all database information'),
    (r'include_files: 是否包含文件信息，默认False以减少响应大小', r'include_files: Whether to include file info, default False to reduce response size'),
    (r'数据库列表', r'List of databases'),
    (r'# 确保元数据已加载（延迟加载机制）', r'# Ensure metadata is loaded (lazy loading mechanism)'),
    (r'将文件添加到处理队列', r'Add file to processing queue'),
    (r'file_id: 文件ID', r'file_id: File ID'),
    (r'从处理队列中移除文件', r'Remove file from processing queue'),
    (r'检查文件是否在处理队列中', r'Check if file is in processing queue'),
    (r'bool: 文件是否在处理队列中', r'bool: Whether the file is in processing queue'),
    (r'检查并修复异常的处理中状态', r'Check and fix anomalous processing status'),
    (r'如果文件状态为处理中但实际不在处理队列中，则修改为相应的错误状态', r'If file status is processing but not actually in the processing queue, change to corresponding error status'),
    (r'# 定义需要检查的中间状态及其对应的错误状态', r'# Define intermediate states to check and their corresponding error states'),
    (r'# 检查该数据库下所有中间状态的文件', r'# Check all intermediate state files under this database'),
    (r'# 如果有状态变更，保存元数据', r'# Save metadata if status changed'),
    (r'删除文件', r'Delete file'),
    (r'获取文件基本信息（仅元数据）', r'Get basic file information (metadata only)'),
    (r'dict: 包含文件基本信息的字典', r'dict: Dictionary containing basic file information'),
    (r'获取文件内容信息（chunks和lines）', r'Get file content information (chunks and lines)'),
    (r'dict: 包含文件内容信息的字典', r'dict: Dictionary containing file content information'),
    (r'获取文件完整信息（基本信息\+内容信息）- 保持向后兼容', r'Get complete file information (basic info + content info) - keep backward compatibility'),
    (r'dict: 包含文件信息和chunks的字典', r'dict: Dictionary containing file info and chunks'),
    (r'获取数据库上传路径', r'Get database upload path'),
    (r'db_id: 数据库ID，可选', r'db_id: Database ID, optional'),
    (r'上传路径', r'Upload path'),
    (r'更新数据库', r'Update database'),
    (r'name: 新名称', r'name: New name'),
    (r'description: 新描述', r'description: New description'),
    (r'llm_info: LLM配置信息（可选，仅用于 LightRAG 类型知识库）', r'llm_info: LLM configuration information (optional, only for LightRAG type knowledge bases)'),
    (r'更新后的数据库信息', r'Updated database information'),
    (r'数据库 \{db_id\} 不存在', r'Database {db_id} not found'),
    (r'# 如果提供了 llm_info，则更新（仅针对 LightRAG 类型）', r'# If llm_info is provided, update (only for LightRAG type)'),
    (r'获取所有检索器', r'Get all retrievers'),
    (r'检索器字典', r'Retriever dictionary'),
    (r'\"\"\"只保存单个文件到数据库，避免全量遍历\"\"\"', r'\"\"\"Only save single file to database to avoid full traversal\"\"\"'),
    (r'\"\"\"只保存单个知识库到数据库，避免全量遍历\"\"\"', r'\"\"\"Only save single knowledge base to database to avoid full traversal\"\"\"')
]

for pattern, repl in translations:
    text = re.sub(pattern, repl, text)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(text)

print('Translation completed for base.py!')
