services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    platform: linux/amd64
    ports:
      - "7474:7474" # Neo4j Browser
      - "7687:7687" # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/testpassword # user: neo4j / pass: testpassword
      - NEO4J_dbms_security_auth__enabled=true
    volumes:
      - ./neo4j_data:/data
      - ./neo4j_logs:/logs
      - ./neo4j_import:/var/lib/neo4j/import
      - ./neo4j_plugins:/plugins
