version: '3.8'

services:
  # --- CORE DATABASE ---
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow_prod_pass_123
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M

  # --- AIRFLOW CORE ---
  airflow-webserver:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/tugas-akhir-airflow:latest
    container_name: airflow-webserver
    restart: always
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow_prod_pass_123@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__PARALLELISM=4
      - AIRFLOW__CORE__DAG_CONCURRENCY=2
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      postgres:
        condition: service_healthy
    command: webserver
    deploy:
      resources:
        limits:
          memory: 800M

  airflow-scheduler:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/tugas-akhir-airflow:latest
    container_name: airflow-scheduler
    restart: always
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow_prod_pass_123@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      postgres:
        condition: service_healthy
    command: scheduler
    deploy:
      resources:
        limits:
          memory: 800M

  # --- NEO4J OPTIMIZED ---
  neo4j:
    image: neo4j:5.15
    container_name: unesa-neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH:-neo4j/rizkyyk123}
      - NEO4J_server_memory_heap_initial__size=256m
      - NEO4J_server_memory_heap_max__size=512m
      - NEO4J_server_memory_pagecache_size=256m
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    ports:
       - "7474:7474"
       - "7687:7687"
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G

  # --- REVERSE PROXY ---
  nginx:
    image: nginx:stable-alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - airflow-webserver
    restart: always

volumes:
  postgres-db-volume:
  neo4j_data:
  neo4j_logs:
