import pytest
import json
from unittest.mock import patch, MagicMock
from knowledge.kg.llm_client import GroqClient
import requests


@pytest.fixture
def mock_groq():
    """Mock the Groq Client with a fake API key so it initializes successfully."""
    return GroqClient(api_key="fake-key", model="fake-model")


@patch("src.kg.llm_client.requests.post")
def test_groq_client_success(mock_post, mock_groq):
    """Test successful JSON response parsing from the Groq API."""
    # Setup mock response
    mock_response = MagicMock()
    mock_response.status_code = 200
    mock_response.json.return_value = {
        "choices": [{"message": {"content": '{"translated": "bonjour"}'}}]
    }
    mock_post.return_value = mock_response

    result = mock_groq.call("Translate hello")

    assert result == {"translated": "bonjour"}
    assert mock_groq.stats["llm_calls"] == 1
    assert mock_groq.stats["llm_errors"] == 0


@patch("src.kg.llm_client.time.sleep")
@patch("src.kg.llm_client.requests.post")
def test_groq_client_retry_on_429(mock_post, mock_sleep, mock_groq):
    """Test exponential backoff triggers on 429 rate limits."""
    # First response is 429, Second is 200 Success
    resp_429 = MagicMock()
    resp_429.status_code = 429

    resp_200 = MagicMock()
    resp_200.status_code = 200
    resp_200.json.return_value = {
        "choices": [{"message": {"content": '{"status": "ok"}'}}]
    }

    mock_post.side_effect = [resp_429, resp_200]

    result = mock_groq.call("Test rate limit")

    assert result == {"status": "ok"}
    # Call was attempted twice
    assert mock_post.call_count == 2
    # Ensure sleep was called to backoff
    mock_sleep.assert_called_with(5)


@patch("src.kg.llm_client.requests.post")
def test_groq_client_handles_json_decode_error(mock_post, mock_groq):
    """Ensure invalid JSON from LLM is caught and retried gracefully."""
    mock_response = MagicMock()
    mock_response.status_code = 200
    # Simulate a bad json response commonly generated by non-json-mode LLMs
    mock_response.json.return_value = {
        "choices": [{"message": {"content": 'This is not JSON!'}}]
    }
    mock_post.return_value = mock_response

    # Should exhaust all 3 retries and return an empty dict
    result = mock_groq.call("Fail json parsing")

    assert result == {}
    assert mock_post.call_count == 3
    assert mock_groq.stats["llm_errors"] == 3
