server {
    listen 80;
    server_name _ tugasakhir.com www.tugasakhir.com;

    # AIRFLOW (Main)
    location / {
        proxy_pass http://airflow-webserver:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
        proxy_read_timeout 300;
        send_timeout 300;
    }

    # NEO4J BROWSER
    location /neo4j/ {
        proxy_pass http://neo4j:7474/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Handling Neo4j internal redirects
    location /browser {
        proxy_pass http://neo4j:7474/browser;
        proxy_set_header Host $host;
    }

    # Grafana trailing slash redirect
    location = /grafana {
        return 301 /grafana/;
    }

    # GRAFANA MONITORING
    location /grafana/ {
        proxy_pass http://grafana:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Prometheus trailing slash redirect
    location = /prometheus {
        return 301 /prometheus/;
    }

    # PROMETHEUS
    location /prometheus/ {
        proxy_pass http://prometheus:9090;  # Notice no trailing slash so it passes /prometheus/ upstream
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
