global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "neo4j"
    static_configs:
      - targets: ["neo4j:7474"]
    metrics_path: /metrics
    scheme: http

  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
