"""
KV Adapter: JSON Key-Value Store for Text Chunks
==================================================
Provides fast chunk_id → content lookup for the GraphRAG pipeline.
Loads the text_chunks.json generated by KG construction (Phase 0).
"""

import json
import logging
from pathlib import Path
from typing import Dict, List, Optional, Any

from ..config import TEXT_CHUNKS_PATH

logger = logging.getLogger(__name__)


class JsonKVStore:
    """JSON-file-backed KV store for text chunk retrieval."""

    def __init__(self, path: Optional[str] = None):
        self.path = Path(path) if path else TEXT_CHUNKS_PATH
        self._data: Dict[str, Dict[str, Any]] = {}
        self._load()

    def _load(self):
        """Load text_chunks.json from disk."""
        if self.path.exists():
            with open(self.path, "r", encoding="utf-8") as f:
                self._data = json.load(f)
            logger.info(f"✅ JsonKVStore loaded {len(self._data)} chunks from {self.path}")
        else:
            logger.warning(f"⚠️ JsonKVStore: {self.path} not found. Run KG pipeline first.")

    def get_by_id(self, chunk_id: str) -> Optional[Dict[str, Any]]:
        """Get a single chunk by ID.

        Args:
            chunk_id: The chunk identifier (e.g., 'chunk_abc123def456').

        Returns:
            Dict with {content, paper_id, title, full_content} or None.
        """
        return self._data.get(chunk_id)

    def get_by_ids(self, chunk_ids: List[str]) -> List[Dict[str, Any]]:
        """Batch retrieval of chunks by IDs.

        Args:
            chunk_ids: List of chunk identifiers.

        Returns:
            List of chunk dicts (skips missing IDs).
        """
        results = []
        for cid in chunk_ids:
            chunk = self._data.get(cid)
            if chunk:
                results.append({**chunk, "chunk_id": cid})
        return results

    def get_by_paper_id(self, paper_id: str) -> Optional[Dict[str, Any]]:
        """Find a chunk by its paper_id."""
        for cid, chunk in self._data.items():
            if chunk.get("paper_id") == paper_id:
                return {**chunk, "chunk_id": cid}
        return None

    @property
    def size(self) -> int:
        return len(self._data)

    def reload(self):
        """Force reload from disk."""
        self._load()
